const THEME_PRIMARY = "#FFC84B"
const THEME_PRIMARY_DARK = "#FFBC23"
const THEME_PRIMARY_LIGHT = "#FDFDDC"

const THEME_SECONDARY = "#4a6572"
const THEME_SECONDARY_DARK = "7C7157"
const THEME_SECONDARY_LIGHT = "324147"

const BLACK = "#212121"
const WHITE = "#fafafa"
const GREY = "#757575"
const DARK_GREY = "#494949"
const LIGHT_GREY = "#a4a4a4"

const info = "#283593"
const STATUS_DELIVERED = "#2979FF"
const STATUS_CREATED =  "#1B5E20"
const STATUS_UNDELIVERED = "#C70039"
const STATUS_OODL = "#4a6572"

export enum Colors{
    THEME_SECONDARY = "#4a6572",
    THEME_PRIMARY = "#FFC84B",
    THEME_PRIMARY_DARK = "#FFBC23",
    THEME_PRIMARY_LIGHT = "#FDFDDC",
    BLACK = "#212121",
    WHITE = "#fafafa",
    GREY = "#757575",
    DARK_GREY = "#494949",
    LIGHT_GREY = "#a4a4a4",
    INFO = "#283593"
}

export enum IconColor{
    THEME_SECONDARY = "#4a6572",
    THEME_PRIMARY = "#FFC84B",
    THEME_PRIMARY_DARK = "#FFBC23",
    THEME_PRIMARY_LIGHT = "#FDFDDC",
    BLACK = "#212121",
    WHITE = "#fafafa",
    GREY = "#757575",
    DARK_GREY = "#494949",
    LIGHT_GREY = "#a4a4a4",
    NAV = "#FFC84B",
    DEAFULT = "#4a6572",
    INFO = "#283593"
}

export const TXT_COLORS ={

    DEAFULT : BLACK,

    PRIMARY : THEME_PRIMARY,
    PRIMARY_DARK : THEME_PRIMARY_DARK,
    PRIMARY_LIGHT: THEME_PRIMARY_LIGHT,

    SECONDARY : THEME_SECONDARY,

    BLACK,
    WHITE,
    GREY,
    DARK_GREY,
    LIGHT_GREY
    
}

export const ICON_COLORS = {
    TAB_BAR_BOTTOM: WHITE,
    HEADER_BAR:THEME_PRIMARY_LIGHT,
    TEXT_BOX:THEME_PRIMARY,
    DASHBOARD:THEME_PRIMARY,
    TAB_BAR_TOP:WHITE,
    NONE:DARK_GREY,

    PRIMARY : THEME_PRIMARY,
    PRIMARY_DARK : THEME_PRIMARY_DARK,
    PRIMARY_LIGHT: THEME_PRIMARY_LIGHT,
    BLACK,
    WHITE,
    GREY,
}

export const COLORS = {

    THEME:THEME_PRIMARY,
    THEME_DARK:THEME_PRIMARY_DARK,
    THEME_LIGHT:THEME_PRIMARY_LIGHT,
    SECONDARY: THEME_SECONDARY,
    SECONDARY_DARK: THEME_SECONDARY_DARK,
    BLACK,
    WHITE,
    GREY,
    DARK_GREY,
    LIGHT_GREY,

    BTN_SUBMIT:"",
    BTN_CANCEL:"",
    BTN_RADIO:"",
    
    BORDER_TXT_BOX:"",
    BORDER_CARD:"#e4e4e4",

    PLACEHOLDER:"",
    
    TXT_PRIMARY:THEME_PRIMARY,

    TXT_HEADER:"",
    TXT_MOVING:"green",

    ICON_NAV_BAR:"",
    ICON_TAB_BAR:"",
    ICON_DESKTOP:"",    

    COLOR_STATUS_OODL : STATUS_OODL,
    COLOR_STATUS_DELIVERED : STATUS_DELIVERED,
    COLOR_STATUS_CREATED :  STATUS_CREATED,
    COLOR_STATUS_UNDELIVERED : STATUS_UNDELIVERED,
    
}

const StatusColor = {
    ABCR: STATUS_CREATED,
    CUCD: STATUS_UNDELIVERED,
    NCIT: STATUS_UNDELIVERED,
    SDCD: STATUS_UNDELIVERED,
    WRIT: STATUS_UNDELIVERED,
    DMGD: STATUS_UNDELIVERED,
    NOAH: STATUS_UNDELIVERED,
    WRAD: STATUS_UNDELIVERED,
    WRPH: STATUS_UNDELIVERED,
    NAPH: STATUS_UNDELIVERED,
    ADCH: STATUS_UNDELIVERED,
    RCDC: STATUS_UNDELIVERED,
    DLVD: STATUS_DELIVERED,
    BRIN: STATUS_UNDELIVERED,
    CGAT: STATUS_UNDELIVERED,
    MMPH: STATUS_UNDELIVERED,
    BOUT: STATUS_UNDELIVERED,
    CHCR: STATUS_UNDELIVERED,
    PCLL: STATUS_UNDELIVERED,
    POFF: STATUS_UNDELIVERED,
    ONHO: STATUS_UNDELIVERED,
    WAWB: STATUS_UNDELIVERED,
    RBA: STATUS_UNDELIVERED,
    RTSD: STATUS_UNDELIVERED,
    VPOD: STATUS_UNDELIVERED,
    OODL: STATUS_OODL,
    AGTC: STATUS_UNDELIVERED,
    AGOH: STATUS_UNDELIVERED,
    CSCL: STATUS_UNDELIVERED,
}

export const getStatusColor = (code:string) =>{
    if(!code) return THEME_PRIMARY
    if(Object.keys(StatusColor).find(colorCode=>colorCode == code)) return StatusColor[code]
}